#
# WARP
# Ansible Galaxy Requirement
#

roles:
  - src: Comcast.sdkman
    version: 1.7.0
  - src: https://github.com/PeterMosmans/ansible-role-customize-gnome
    version: 0.2.12
collections:
  - name: community.general
    version: 11.4.1
  - name: ansible.posix
    version: 2.1.0
