#
# WARP
# Dotfiles Ansible Role
# Default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: 58f81275458bff9efe0edc0babe4f305a31356e2
