#
# WARP
# Dotfiles Ansible Role
# Default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: ad5215930d2aa5a3cc8de91260ec8a256e9bcb63
