#
# WARP
# Neovim Ansible Role
# Default Variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# Neovim text editor
# renovate: datasource=github-releases depName=neovim/neovim
devbox_nvim_version: v0.11.4
# renovate: datasource=github-releases depName=folke/lazy.nvim
devbox_nvim_lazy_version: v10.24.3
# renovate: datasource=pip depName=codespell
devbox_codespell_version: 2.4.1
